apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    role: cache
  name: nginx-with-redis
  namespace: default
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        role: nginx-with-redis-instance
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      - name: redis
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379

