version: '3'

services:
  mysql:
    image: mysql:5.6.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=sampleUser
      - MYSQL_PASSWORD=samplePass
      - MYSQL_DATABASE=sampleDb
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - "db-data:/var/lib/mysql"

volumes:
  db-data:
