version: '3'

services:
  mysql:
    image: mysql:5.6.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=sampleUser
      - MYSQL_PASSWORD=samplePass
      - MYSQL_DATABASE=sampleDb
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - "db-data:/var/lib/mysql"
  redis:
    image: redis
    ports:
      - "6379:6379"
  s3:
    image: minio/minio:RELEASE.2017-08-05T00-00-53Z
    ports:
      - "9000:9000"
    volumes:
      - "s3-data:/data"
      - "s3-config-data:/root/.minio"
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
  application:
    image: sample_todos:1.0
    ports:
      - "3000:3000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=sampleUser
      - MYSQL_PASS=samplePass
      - MYSQL_DB=sampleDb
      - AWS_ACCESS_KEY=minio
      - AWS_SECRET_KEY=minio123
      - AWS_REGION=us-east-1
      - AWS_ENDPOINT=http://s3
      - AWS_PORT=9000
      - AWS_S3_BUCKET=docker-local-sample-bucket
      - IMAGE_ENDPOINT=http://127.0.0.1:9000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - "/path/to/Chapter04/sampleCode/editDockerApplicationSample/todos:/app"
      - "/app/node_modules"
    depends_on:
      - mysql
      - redis
      - s3
  mc:
    image: minio/mc:RELEASE.2017-06-15T03-38-43Z
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    depends_on:
      - s3

volumes:
  db-data:
  s3-data:
  s3-config-data:
