version: '3'

services:
  mysql:
    image: mysql:5.6.35
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=sampleUser
      - MYSQL_PASSWORD=samplePass
      - MYSQL_DATABASE=sampleDb
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - "db-data:/var/lib/mysql"
  redis:
    image: redis
    ports:
      - "6379:6379"
  s3:
    image: minio/minio:RELEASE.2017-08-05T00-00-53Z
    ports:
      - "9000:9000"
    volumes:
      - "s3-data:/data"
      - "s3-config-data:/root/.minio"
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123

volumes:
  db-data:
  s3-data:
  s3-config-data:
